export const skillset = [
  "React JS",
  "Next JS",
  "GraphQL",
  "TypeScript",
  "JavaScript",
  "Shopify / Liquid",
  "Sass / SCSS",
  "UX / UI",
  "MySQL",
  "Node JS",
  "Express JS",
  "JSON",
  "REST",
  "HTML 5",
  "CSS 3",
  "Styled Components",
  "SPAs",
  "Responsive Web Development",
  "GitHub",
  "VTEX",
  "Sitecore",
  "Salesforce / Heroku",
  "Adobe Suite",
];
