export const skillset = [
  "React JS 18",
  "Next JS 12/13",
  "GraphQL",
  "TypeScript",
  "JavaScript",
  "Sass / SCSS",
  "UX / UI",
  "MySQL",
  "Node JS",
  "Express JS",
  "VTEX",
  "JSON",
  "JQuery",
  "REST",
  "HTML 5",
  "CSS 3",
  "Styled Components",
  "SPAs",
  "Responsive Web Development",
  "GitHub",
  "Salesforce / Heroku",
  "Adobe Suite",
];
